# Generated by Django 4.1.3 on 2022-11-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_customers_order_customer'),
        ('app', '0004_order'),
    ]

    operations = [
    ]
